export enum events
{
    'closeOverlay',
    'deleteTodo',
    'addTodo',
    'saveTodo',
    'deletePomodoro',
    'showOrHidePanelPomodoro',
    'showOrHideTodoPanel',
    'destroyTodoPanel',
    'destroyPomodoroPanel',
    'openOverlay',
    'switchPanel',
    'switchView',
    'cancelEdit',
    'updateSettings',
    'openSettings',
    'closeSettings',
    'reset'
}